### ISSUE TITLE
Vestaboard Local API

### ISSUE THREAD

**Issue by sebbo2002** [mark-thomas/vestaboard-api#22]
Is the [Vestaboard Local API](https://docs.vestaboard.com/local) something you can imagine adding to this great library in the future? Or is it better to look for alternatives?

I use your library within [vestaboard2mqtt](https://github.com/sebbo2002/vestaboard2mqtt) to connect my Vestaboard with the local home automation system and I think about making this connection local-only.

**Comment by mark-thomas** [comment]
Sorry, haven't been paying much attention to this over the last few months.

I took a look at the local api a little and I think it could be added. I'll see if I can do that sometime soon.

**Comment by sebbo2002** [comment]
Haha, all good. I assumed that the project is dead and therefore implemented [my own library](https://github.com/sebbo2002/vestaboard), which implements all the current APIs including the Local API. So please don't stress from my side, I'm taken care of by now. Thanks anyway. Should I close the ticket?

**Comment by mark-thomas** [comment]
Finally got around to this. Better late than never I guess. :)
